name: Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug]
body:
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **DIM Version**: Version 6.78.0.1000630 (beta), built on 8/15/2021, 8:04:14 PM (Find the version in "About DIM" from the menu (the button with three bars on the upper left of the screen). Is the DIM icon orange, or blue?)
        - **Browser**: Chrome 92.0.4515.131
        - **OS**: Windows 10
    value: |
        - DIM Version:
        - Broswer:
        - OS:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: Tell us what's wrong. A great format for bug reports is "I did X, and I expected Y, but instead Z happened." If it helps illustrate the issue, please add screenshots to help explain your problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: If you can, open the devtools console (ctrl+shift+J on PC and cmd+option+J on Mac) and paste what you see in the window that pops up
  validations:
    required: false