name: Verify CHANGELOG.md Updated
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]

jobs:
  changelog:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: CHANGELOG.md Check
          uses: Zomzog/changelog-checker@v1.2.0
          with:
            fileName: docs/CHANGELOG.md
            checksNotification: Simple
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}