on: push
name: packtracker.io
jobs:
  report:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: report webpack stats
        uses: delphiactual/report@2.3.1
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
          WEBPACK_CONFIG_PATH: ./config/webpack.js